version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
