package main

// `clawall gateway init` — one-shot setup wizard. Generates a CA,
// writes a sane wireguard-mode gateway.yaml, opens firewall ports,
// and prints the run command. Replaces the bash-script deploy hacks.

import (
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

func runGatewayInit(args []string) {
	fs := flag.NewFlagSet("gateway init", flag.ExitOnError)
	dataDir := fs.String("data-dir", "/etc/clawall", "where to put gateway.yaml + CA + state")
	publicURL := fs.String("public-url", "", "public dashboard URL (auto-detected from public IP if empty)")
	publicIP := fs.String("public-ip", "", "public IP for the WG endpoint (auto-detected if empty)")
	adminEmail := fs.String("admin-email", "", "operator email — owner of all approved devices")
	wgPort := fs.Int("wg-port", 51820, "wireguard UDP port")
	dashPort := fs.Int("dash-port", 9080, "dashboard / onboard HTTP port")
	tlsPort := fs.Int("tls-port", 8443, "TLS gateway port (host kernel — does NOT need to be public)")
	subnet := fs.String("subnet", "10.55.0.0/24", "wireguard subnet pool")
	skipFirewall := fs.Bool("no-firewall", false, "skip iptables ACCEPT rules")
	_ = fs.Parse(args)

	if *adminEmail == "" {
		fmt.Fprintln(os.Stderr, "missing --admin-email (the operator's identity for OAuth credential ownership)")
		os.Exit(2)
	}

	// 1. data dir + CA -----------------------------------------------------
	if err := os.MkdirAll(filepath.Join(*dataDir, "ca"), 0o700); err != nil {
		fail("mkdir ca: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(*dataDir, "oauth"), 0o700); err != nil {
		fail("mkdir oauth: %v", err)
	}
	caPath := filepath.Join(*dataDir, "ca", "ca.crt")
	if _, err := os.Stat(caPath); err != nil {
		fmt.Println("==> generating CA")
		if err := writeCA(filepath.Join(*dataDir, "ca")); err != nil {
			fail("init-ca: %v", err)
		}
	} else {
		fmt.Println("==> CA exists, keeping")
	}

	// 2. detect public IP if not given -------------------------------------
	ip := *publicIP
	if ip == "" {
		fmt.Println("==> detecting public IP via ifconfig.me")
		ip = detectPublicIP()
		if ip == "" {
			fail("couldn't detect public IP — pass --public-ip explicitly")
		}
		fmt.Printf("    %s\n", ip)
	}
	url := *publicURL
	if url == "" {
		url = fmt.Sprintf("http://%s:%d", ip, *dashPort)
	}

	// 3. write gateway.yaml ------------------------------------------------
	cfgPath := filepath.Join(*dataDir, "gateway.yaml")
	cfg := fmt.Sprintf(`# generated by clawall gateway init
listen: "0.0.0.0:%d"
info_listen: "0.0.0.0:%d"
public_url: "%s"
admin_email: "%s"
ca_dir: "%s"
log_path: "%s"
oauth_dir: "%s"

integrations:
  - claude
  - codex
  - github

tailscale:
  control: wireguard
  wg_endpoint: "%s:%d"
  wg_subnet_cidr: "%s"

demo: false
rules: []
`,
		*tlsPort, *dashPort, url, *adminEmail,
		filepath.Join(*dataDir, "ca"),
		filepath.Join(*dataDir, "gateway.log"),
		filepath.Join(*dataDir, "oauth"),
		ip, *wgPort, *subnet,
	)
	if err := os.WriteFile(cfgPath, []byte(cfg), 0o644); err != nil {
		fail("write %s: %v", cfgPath, err)
	}
	fmt.Printf("==> wrote %s\n", cfgPath)

	// 4. open firewall ports (best-effort) ---------------------------------
	if !*skipFirewall {
		fmt.Println("==> opening firewall ports")
		openFirewallPort("udp", *wgPort)
		openFirewallPort("tcp", *dashPort)
	}

	// 5. systemd unit (if systemd is around) -------------------------------
	if _, err := exec.LookPath("systemctl"); err == nil {
		writeSystemdUnit(*dataDir, cfgPath)
	}

	fmt.Printf(`
done. start the gateway:

    systemctl enable --now clawall-gateway        # if systemd available
or:
    clawall gateway -config %s

dashboard: %s
new-client onboarding: clawall join --url %s
`, cfgPath, url, url)
}

// detectPublicIP queries plain-text IP echo services. We validate
// the response is something IP-shaped rather than an HTML page (some
// services serve a captcha page from non-residential IPs).
func detectPublicIP() string {
	endpoints := []string{
		"https://ipv4.icanhazip.com",
		"https://api.ipify.org",
		"https://ifconfig.me/ip",
		"https://checkip.amazonaws.com",
	}
	c := &http.Client{Timeout: 5 * time.Second}
	for _, u := range endpoints {
		req, _ := http.NewRequest("GET", u, nil)
		req.Header.Set("User-Agent", "curl/8")
		resp, err := c.Do(req)
		if err != nil {
			continue
		}
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 64))
		resp.Body.Close()
		ip := strings.TrimSpace(string(b))
		if isIPv4(ip) {
			return ip
		}
	}
	return ""
}

func isIPv4(s string) bool {
	parts := strings.Split(s, ".")
	if len(parts) != 4 {
		return false
	}
	for _, p := range parts {
		if p == "" || len(p) > 3 {
			return false
		}
		for _, c := range p {
			if c < '0' || c > '9' {
				return false
			}
		}
	}
	return true
}

func openFirewallPort(proto string, port int) {
	chk := runAsRoot("iptables", "-C", "INPUT", "-p", proto, "--dport", fmt.Sprint(port), "-j", "ACCEPT")
	if chk.Run() == nil {
		fmt.Printf("    %s/%d already open\n", proto, port)
		return
	}
	add := runAsRoot("iptables", "-I", "INPUT", "-p", proto, "--dport", fmt.Sprint(port), "-j", "ACCEPT")
	if err := add.Run(); err != nil {
		fmt.Printf("    ⚠ couldn't open %s/%d: %v (you may need to add it manually)\n", proto, port, err)
		return
	}
	fmt.Printf("    opened %s/%d\n", proto, port)
}

func writeSystemdUnit(dataDir, cfgPath string) {
	const path = "/etc/systemd/system/clawall-gateway.service"
	if _, err := os.Stat(path); err == nil {
		fmt.Printf("==> %s exists, keeping\n", path)
		return
	}
	exe, _ := os.Executable()
	if exe == "" {
		exe = "/usr/local/bin/clawall"
	}
	unit := fmt.Sprintf(`[Unit]
Description=clawall gateway
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=%s
EnvironmentFile=-%s/secrets.env
ExecStart=%s gateway -config %s
Restart=on-failure
RestartSec=2
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
`, dataDir, dataDir, exe, cfgPath)

	if err := os.WriteFile(path, []byte(unit), 0o644); err != nil {
		fmt.Printf("    ⚠ couldn't write %s: %v\n", path, err)
		return
	}
	_ = runAsRoot("systemctl", "daemon-reload").Run()
	fmt.Printf("==> wrote %s\n", path)
}
